export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';

export const SHIPPING_ADDRESS_ADD = 'SHIPPING_ADDRESS_ADD';
export const SHIPPING_ADDRESS_REMOVE = 'SHIPPING_ADDRESS_REMOVE';

export const PAYMENT_METHOD_ADD = 'PAYMENT_METHOD_ADD';
export const CART_CLEAR = 'CART_CLEAR';