# Generated by Django 3.2.11 on 2022-02-15 12:23

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
